version: "3.7"
services:
  app:
    image: cipher_api:0.1
    build:
      context: ./
      dockerfile: Dockerfile_app
    container_name: cipher_api
    expose:
      - "5000"
  nginx:
    image: cipher_nginx:0.1
    build:
      context: ./
      dockerfile: Dockerfile_nginx
    links:
      - app
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
