name: Build backend app image

on:
  push:
    paths: app-backend/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1
      name: Build and push creeptoo backend docker image
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: app-backend
        repository: dkder3k/creeptoo-backend
        tags: latest, $(date +%s)
