name: Build backend app image

on:
  push:
    branches: [ master ]

jobs:
  docker_build:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        name: Build and push creeptoo backend docker image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: app-backend
          repository: dkder3k/creeptoo-backend
          tags: latest, $(date +%s)
